<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="WOW Slider, jQuery Fading Slideshow, Background Slideshow jQuery" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
<style type="text/css">
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
</style>
</head>
<body style="background-color:$PageBgColor$">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/minislider1.jpg" alt="mini-slider-1" title="mini-slider-1" id="wows1_0"/></li>
<li><img src="data1/images/minislider2.jpg" alt="mini-slider-2" title="mini-slider-2" id="wows1_1"/></li>
<li><img src="data1/images/minislider3.jpg" alt="mini-slider-3" title="mini-slider-3" id="wows1_2"/></li>
<li><img src="data1/images/minislider4.jpg" alt="mini-slider-4" title="mini-slider-4" id="wows1_3"/></li>
<li><img src="data1/images/minislider5.jpg" alt="mini-slider-5" title="mini-slider-5" id="wows1_4"/></li>
<li><img src="data1/images/minislider6.jpg" alt="mini-slider-6" title="mini-slider-6" id="wows1_5"/></li>

</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="mini-slider-1"><img src="data1/tooltips/minislider1.jpg" alt="mini-slider-1"/>1</a>
<a href="#" title="mini-slider-2"><img src="data1/tooltips/minislider2.jpg" alt="mini-slider-2"/>2</a>
<a href="#" title="mini-slider-3"><img src="data1/tooltips/minislider3.jpg" alt="mini-slider-3"/>3</a>
<a href="#" title="mini-slider-4"><img src="data1/tooltips/minislider4.jpg" alt="mini-slider-4"/>4</a>
<a href="#" title="mini-slider-5"><img src="data1/tooltips/minislider5.jpg" alt="mini-slider-5"/>5</a>
<a href="#" title="mini-slider-6"><img src="data1/tooltips/minislider6.jpg" alt="mini-slider-6"/>6</a>
</div></div>

	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>